config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks, except: [:index, :show]
  end

  devise_for :users

  get 'pages/about', as: :about
  get 'pages/features', as: :features
  get 'pages/contact', as: :contact

  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  enum status: { draft: 0, published: 1, completed: 2, archived: 3 }

  scope :active, -> { where active: true }
  scope :order_by_latest, -> { order created_at: :desc }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project
  enum status: { to_do: 0, complete: 1 }
  
  validates :name, presence: true
  validates :description, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def features
  end

  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  def index
    @projects = Project.active.order_by_latest
  end

  def show
    @users = User.all
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to @project, notice: "Project was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url
  end

  private
    def set_project
      @project = Project.includes(:tasks).find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description, :due_date, :status, :active)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[ edit update destroy ]
  before_action :set_project, only: %i[ new edit update create destroy ]

  def new
    @task = Task.new
  end
  
  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.project_id = params[:project_id]
    
    if @task.save
      respond_to do |format|
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @task.update(task_params)
      respond_to do |format|
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @task.destroy
      respond_to do |format|
        format.turbo_stream
      end
    end
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def task_params
      params.require(:task).permit(:name, :description, :status, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_due_date project
    if project.due_date.present?
      Time.now > project.due_date ? "Project overdue by #{ time_ago_in_words(project.due_date) }" : "Due in #{ time_ago_in_words(project.due_date) } from now"
    else
      "No due date set for this project"
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_alerts.html.erb
<%= content_tag :p, notice, class: "alert alert-success" if notice %>
<%= content_tag :p, alert, class: "alert alert-danger" if alert %>

app/views/layouts/_footer.html.erb
<footer class="border-top mt-5 pt-4">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <nav class="list-inline small">
          <li class="list-inline-item"><%= link_to "Home", root_path %></li>
          <li class="list-inline-item"><%= link_to "About", about_path %></li>
          <li class="list-inline-item"><%= link_to "Features", features_path %></li>
          <li class="list-inline-item"><%= link_to "Contact", contact_path %></li>
        </nav>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_modal.html.erb
<div class="modal fade" tabindex="-1" data-controller="modal" data-action="turbo:frame-load->modal#open turbo:submit-end->modal#close" role="dialog" aria-labelledby="bootstrapModal" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
      <%= turbo_frame_tag "modal" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<header class="bg-light pt-3 pb-2 mb-5">
  <div class="container">
    <div class="row">
      <div class="col-4 col-xl-2">
        <p class="lead">Project Turbo</p>
      </div>
      <div class="col-8 col-xl-10 text-end">
        <nav class="">
          <ul class="list-inline m-0">
            <li class="list-inline-item"><%= link_to "Home", root_path %></li>
            <li class="list-inline-item"><%= link_to "Projects", projects_path %></li>
            <% if user_signed_in? %>
              <li class="list-inline-item"><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-secondary" %></li>
            <% else %>
              <li class="list-inline-item"><%= link_to "Sign In", new_user_session_path %></li>
              <li class="list-inline-item"><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success" %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_validation.html.erb
<% if record.errors.any? %>
  <div class="mt-3 mb-4">
    <p><%= pluralize(record.errors.count, "error") %> prohibited this <%= record.class.name %> from being saved:</p>

    <ul>
      <% record.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Management App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render partial: "layouts/nav" %>

    <main>
      <div class="container">
        <div class="row">
          <div class="col-12">
            <%= render partial: "layouts/alerts" %>
            <%= yield %>
          </div>
        </div>
      </div>
    </main>

    <%= render "layouts/modal" %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/features.html.erb
<h1>Pages#features</h1>
<p>Find me in app/views/pages/features.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <%= render partial: "layouts/validation", locals: { record: project } %>

  <div class="form-group mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :due_date, class: "form-label" %>
    <%= form.datetime_field :due_date, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit "Save Project", class: "btn btn-success" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>" class="project border rounded p-3 mb-3 bg-light">
  <%= link_to "View Project", project_path(project), class: "float-end btn btn-outline-primary" %>
  <p class="lead mb-0"><%= link_to project.name, project_path(project), class: "text-dark text-decoration-none" %></p>
  <%= content_tag :p, truncate(project.description, length: 50), class: "text-muted" %>
</div>

app/views/projects/_summary.html.erb
<div id="summary">
  <ul>
    <li><%= project_due_date(project) %></li>
    <li><span id="tasks-completed"><%= pluralize(project.tasks.complete.size, "task") %></span> completed</li>
    <li><span id="tasks-outstanding"><%= pluralize(project.tasks.to_do.size, "task") %></span> outstanding</li>
  </ul>
</div>

app/views/projects/create.turbo_stream.erb
<%= turbo_stream.prepend "projects", @project %>
<%= turbo_stream.replace "total_projects", pluralize(Project.active.size, "project") %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path, data: { turbo_frame: "modal" }, class: "btn btn-success float-end" %>

<h1>Projects</h1>
<p>Showing <span id="total_projects"><%= pluralize(@projects.size, "project") %></span></p>

<div id="projects" class="mt-5">
  <% @projects.each do |project| %>
    <%= render project %>
  <% end %>
</div>

app/views/projects/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <h1>New project</h1>
  <%= render "form", project: @project %>
<% end %>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-12 col-md-8">
    <div id="project-details">
      <h1><%= @project.name %></h1>
      <%= simple_format @project.description %>

      <p>
        <%= link_to "Edit this project", edit_project_path(@project), class: "text-muted" %> |
        <%= link_to "Back to projects", projects_path, class: "text-muted" %>
      </p>
    </div>

    <div class="bg-light mt-5 p-4 rounded">
      <%= link_to "New Task", new_project_task_path(@project), data: { turbo_frame: "modal" }, class: "btn btn-primary float-end" %>
      <h2>Project Tasks</h2>
    </div>
    <div id="tasks">
      <% @project.tasks.each do |task| %>
        <%= render task %>
      <% end %>
    </div>
  </div>
  <div class="col-12 col-md-4">
    <h2>Summary</h2>
    <%= render partial: "projects/summary", locals: { project: @project } %>
  
    <h2>Team Members</h2>
    <p><small><%= pluralize(@users.size, "users") %> have access to this project</small></p>
    <ul>
      <% @users.each do |user| %>
        <li><%= user.username.capitalize %></li>
      <% end %>
    </ul>

    <%= link_to "Delete Project", @project, class: "btn btn-outline-danger", data: { turbo_confirm: "Are you sure you want to delete this project?", turbo_method: :delete } %>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task, url: [@project, task]) do |form| %>
  <%= render partial: "layouts/validation", locals: { record: task } %>

  <div class="form-group mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :user_id, class: "form-label" %>
    <%= form.select :user_id, User.all.collect {|u| [u.username.capitalize, u.id] }, {}, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :status, class: "form-label" %>
    <%= form.select :status, options_for_select(Task.statuses.keys.map{|s| [s.titleize, s]}, task.status), {}, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit "Save Task", class: "btn btn-success" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>" class="border-bottom p-3 mb-3">
  <div class="float-end text-end">
    <%= button_to "Mark as Complete", project_task_path(task.project_id, task, task: { status: 'complete' }), method: :patch, class: "btn btn-sm btn-outline-secondary mb-2" unless task.complete? %>
    <%= link_to "Delete Task", project_task_path(task.project_id, task), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this task?" }, class: "text-secondary small" %>
  </div>
  <p class="lead mb-0"><%= link_to task.name, edit_project_task_path(task.project_id, task), data: { turbo_frame: "modal" }, class: "text-dark #{'text-muted text-decoration-line-through' if task.complete? }" %></p>
  <%= content_tag :p, truncate(task.description, length: 50), class: "text-muted mb-1" %>
  <p><small>Assigned to <%= task.user.username.titleize %></small></p>
</div>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.prepend "tasks", @task %>
<%= turbo_stream.replace "summary", partial: "projects/summary", locals: { project: @project } %>

app/views/tasks/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@task) %>
<%= turbo_stream.replace "summary", partial: "projects/summary", locals: { project: @project } %>

app/views/tasks/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <h1>Editing task</h1>
  <%= render "form", task: @task %>
<% end %>

app/views/tasks/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <h1>New task</h1>
  <%= render "form", task: @task %>
<% end %>

app/views/tasks/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@task), partial: "tasks/task", locals: { task: @task } %>
<%= turbo_stream.replace "summary", partial: "projects/summary", locals: { project: @task.project } %>